version: "3.8"

networks:
  web_network:
    driver: bridge
    internal: true
  external_network:
    driver: bridge

services:
  mysql:
    container_name: aplicacaoMysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: urubu100
      MYSQL_DATABASE: aulaSO
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - web_network

  node:
    container_name: aplicacaoNode
    image: marcelofocmenezes/node-eyesanalytic:latest
    restart: always
    ports:
      - "8080:8080"
    networks:
      - web_network
      - external_network

volumes:
  mysql_data:
