version: "3.8"

networks:
  web_network:
    driver: bridge
  external_network:
    driver: bridge

services:
  mysql:
    container_name: aplicacaoMysql
    image: mysql:8:0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: urubu100
      MYSQL_DATABASE: eyesAnalytic
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql  # Garantindo persistência dos dados
    ports:
      - "3306:3306"  # Expondo a porta 3306 para acesso externo
    networks:
      - web_network
      - external_network  # Permitir a comunicação também na rede externa

  node:
    container_name: aplicacaoNode
    image: marcelofocmenezes/node-eyesanalytic:latest
    restart: always
    ports:
      - "8080:8080"
    networks:
      - web_network
      - external_network

volumes:
  mysql_data:
